# config/aruco_loc.yaml
# Parameters for ArUco localization

---
/**:
    ros__parameters:

      general:
        marker_count: 2             # Number of tags in the World
        marker_size: 0.16           # Width of the ArUco tags [m]
        detection_rate: 1.0         # Maximum detection frequency for pose update
        world_frame_id: "map"       # Frame id of the world frame

      marker_000:
        aruco_id: 43                # ID of the ArUco tag as retrieved by the ArUco Detector code
        position: [0.0,0.0,0.7]         # Pose with respect to the World origin [m]
        orientation: [0.0,0.0,0.0]  # Orientation with respect to the World origin [rad]

      marker_001:
        aruco_id: 19                # ID of the ArUco tag as retrieved by the ArUco Detector code
        position: [1.08,0.45,1.145]     # Pose with respect to the World origin [m]
        orientation: [0.0,0.0,0.0]  # Orientation with respect to the World origin [rad]

      # Add a number of marker definitions equal to the number of markers in the World
      
      #marker_xxx:
      #  aruco_id: YYY               # ID of the ArUco tag as retrieved by the ArUco Detector code
      #  position: [x.x,y.y,z.z]         # Pose with respect to the World origin [m]
      #  orientation: [R.R,P.P,Y.Y]  # Orientation with respect to the World origin [rad]