# config/aruco_loc.yaml
# Parameters for ArUco localization

---
/**:
    ros__parameters:

      general:
        marker_count: 1             # Number of tags in the World

      marker_001:
        aruco_id: 1                 # ID of the ArUco tag as retrieved by the ArUco Detector code
        pose: [0.0,0.0,0.0]         # Pose with respect to the World origin
        orientation: [0.0,0.0,0.0]  # Orientation with respect to the World origin

      # Add a number of marker definitions equal to the number of markers in the World
      
      #marker_002:
      #  aruco_id: ZZZ                # ID of the ArUco tag as retrieved by the ArUco Detector code
      #  pose: [x.x,y.y,z.z]         # Pose with respect to the World origin
      #  orientation: [R.R,P.P,Y.Y]  # Orientation with respect to the World origin

      #marker_xxx:
      #  aruco_id: YYY               # ID of the ArUco tag as retrieved by the ArUco Detector code
      #  pose: [x.x,y.y,z.z]         # Pose with respect to the World origin
      #  orientation: [R.R,P.P,Y.Y]  # Orientation with respect to the World origin